"""Phase 17 Feature Leakage Audit Script for LightGBM Feature Schema."""
import sys
import pandas as pd
import numpy as np
from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT_DIR))

# Force UTF-8 stdout on Windows
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from app.evaluation.lightgbm_feature_builder import LightGBMFeatureBuilder

def test_explicit_leakage_cases():
    """Tests explicit forbidden future-reference feature leakage patterns."""
    print("=======================================================")
    print("  LIGHTGBM FEATURE LEAKAGE AUDIT")
    print("=======================================================")

    builder = LightGBMFeatureBuilder()

    # Synthetic sample OHLCV data
    dates = pd.date_range("2026-01-01", periods=100, freq="1D")
    df = pd.DataFrame({
        "timestamp": dates.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "open": np.linspace(100, 150, 100),
        "high": np.linspace(102, 152, 100),
        "low": np.linspace(98, 148, 100),
        "close": np.linspace(101, 151, 100),
        "volume": np.random.randint(1000, 5000, 100)
    })

    # 1. Audit features generated by feature builder
    clean_df = builder.build_features_and_target(df)
    audit_res = builder.audit_feature_leakage(clean_df)
    
    assert audit_res["passed"] is True
    print("  [OK] Standard feature schema audit PASSED (0 look-ahead features)")

    # 2. Test explicit forbidden feature names (e.g. shift(-1), future_close)
    df_leak = clean_df.copy()
    df_leak["future_close_leakage"] = df_leak["close"].shift(-1)
    
    # Audit should detect invalid future feature name if injected into schema
    bad_features = [col for col in df_leak.columns if "future" in col and col != "target_return_4bar"]
    assert "future_close_leakage" in bad_features
    print("  [OK] Forbidden future-referencing feature 'future_close_leakage' correctly flagged")

    # 3. Target Alignment Audit: target[t] == close[t+4] / close[t] - 1
    t0_close = clean_df["close"].iloc[0]
    t4_close = clean_df["future_close"].iloc[0]
    expected_target = (t4_close / t0_close) - 1.0
    actual_target = clean_df["target_return_4bar"].iloc[0]

    assert abs(actual_target - expected_target) < 1e-6
    print(f"  [OK] Target alignment verified: t0={t0_close:.2f}, t4={t4_close:.2f}, target={actual_target:.6f}")

    print("=======================================================")
    print("  LIGHTGBM FEATURE LEAKAGE AUDIT PASSED")
    print("=======================================================")

if __name__ == "__main__":
    test_explicit_leakage_cases()
